### ISSUE TITLE
Laravel 5.8 Compatiblity - Project abandoned?

### ISSUE THREAD

**Issue by w00p** [poowf/otter#41]
Hi, is this project abandoned? Cant get it to work on latest laravel 5.8.

**Comment by zanechua** [comment]
No. This project is not abandoned.

I haven't had time to test this with Laravel 5.8 but what errors do you get?

I'll have some time to check it out on 5.8

**Comment by zanechua** [comment]
Just did a quick run through and it turns out some of the method names have changed for relationships.

`getForeignKey` was rename to `getForeignKeyName` in the following commit:

https://github.com/laravel/framework/commit/294c006288ee182eeddf3c6deb23a35032a9219d

Looks like I'll have to make a version that's compatible with Laravel 5.8+

**Comment by zanechua** [comment]
The helpers have also been deprecated and requires fixing:

https://github.com/laravel/framework/pull/26898

**Comment by zanechua** [comment]
The develop branch works with Laravel 5.8.

Need a little bit more testing before I merge it in with master

**Comment by w00p** [comment]
Superb! Will check it out when i have the time.

**Comment by zanechua** [comment]
No breaking issues have been seen in Laravel 5.8 with the latest version of develop. Will be closing this.
